### PR TITLE
Price of Bitcoin and Ether/Settings

### PR DESCRIPTION
**Pull request by clarencejychan**
# Description

Added `axios` as a package to use as a dependency for requests. Created the price function in order to fetch the relevant information from the cryptonator api.

Also added in some of the settings stuff. I still need to finish up the currency selector and another ticket probably needs to be opened up such that the currency selector actually changes things. I'm using a placeholder icon for now as I don't have the PNG's for the other ones. I checked on Figma, but you can only export them as SVG's or CSS? 

Fixes: # (issue)
#11 #10 
## Type of change
Enhancement
# Screenshots (if applicable):

### CODE REVIEW

**Comment by clarencejychan** [comment]
@alvesjtiago , the issue stated that we wanted to automatically update the price. I'm assuming that this would be done on the holdings level. I'm wondering if we're gonna separate holdings into fiat and non-fiat holdings since we can't call this api for fiat holdings. A simple fix would be just to check what the holding actually is and decide to call it or not, but not sure if there's a more long-term plan in place for this.

**Comment by alvesjtiago** [comment]
@clarencejychan sorry for taking so long to reply but I was out this week. Have you had a chance to try the iOS app? We're using https://exchangeratesapi.io/ there and it would be great to use the same for the web version. That way regardless of it being crypto or fiat the structure would be the same.

I'll be reviewing your PR this week and organizing the next steps. Thank you once again for your contribution 🙏

**Comment by alvesjtiago** [comment]
So after we get get crypto or fiat exchange rate we'll be storing it on the currencies model as the `euro_rate`. Here's the corresponding iOS code: https://github.com/lannister-capital/lannister-ios/blob/cb07a14952b3682faf34b55c1b52eeb8c5f45c1c/Lannister/AppDelegate.swift#L277

**Comment by clarencejychan** [comment]
@alvesjtiago I see, I"ll take a look at some of the iOS code to see how that works. I'm wondering about how we separate each individual holding to show the updated values based on the APIs. Since regardless of fiat or crypto, it's still a "holding", in the iOS app, are there just checks to see if the holding is crypto or fiat and then the appropriate API is called to update the price to show the user?

**Comment by alvesjtiago** [comment]
The euro_rate of the currency (fiat or crypto) is always updated when the app opens so it doesn't really matter if a holding is fiat or crypto. Let me know if I'm not explaining this clearly and we can jump on a quick call on discord 😊

**Comment by clarencejychan** [comment]
I think I understand a little bit better now that I mulled over it for a bit. I'll be sure to take a deeper look into the iOS code before I do any implementation. I haven't had the time this week as had some family visiting. Thanks for the clarity and I"ll definitely hop on a call with you (if your time permits) if I have any more confusion!

Thanks @alvesjtiago

**Pull request merged**
